services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: spotify_php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - APP_ENV=dev
      - APP_SECRET=bf5c8b0d4adab7c2db8bc7b3e1d7f4e5a8b1c3d6e9f2a5b8c1d4e7f0a3b6c9d2
      - DATABASE_URL=mysql://spotify_user:spotify_password@mysql:3306/spotify_db?serverVersion=8.0
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spotify_db
      - MYSQL_USER=spotify_user
      - MYSQL_PASSWORD=spotify_password
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /var/www/html
    networks:
      - spotify_network

  nginx:
    image: nginx:alpine
    container_name: spotify_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - spotify_network

  mysql:
    image: mysql:8.0
    container_name: spotify_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotify_db
      MYSQL_USER: spotify_user
      MYSQL_PASSWORD: spotify_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    networks:
      - spotify_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: spotify_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spotify_network

volumes:
  mysql_data:
    driver: local

networks:
  spotify_network:
    driver: bridge